name: Tests
on:
  push:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest-16-cores
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm test
